FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    coreutils \
    git \
    curl \
    build-essential \
    gh \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

WORKDIR /app

COPY . /app/

ENTRYPOINT ["/bin/bash"]