name: Packaging
 
on:
  push: [main]
  
jobs:
  build-packaging-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t id-mlip -f Dockerfile.packaging .
  
  run-packaging-container:
  needs: build-packaging-image
  runs-on: ubuntu-latest
  run: |
    docker run -it id-mlip

  publish-mlip-package:
    needs: run-packaging-container
    runs-on: ubuntu-latest
    steps:
      - name: build package
        run: |
          
          cd open-sourcing
          echo "starting build"
          python setup.py sdist bdist_wheel
          echo "build finished"



  