name: Packaging
 
on: 
  push:
    branches: [release-202503191002]

jobs:

  publish-mlip-package:
    needs: build-packaging-image
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: build package
        run: |
          pwd
          cd open-sourcing
          echo "starting build"
          python setup.py sdist bdist_wheel
          echo "build finished"



  