name: Packaging
 
on: 
  push:
    branches: [release-202503191002]

jobs:

  publish-mlip-package:
    # needs: build-packaging-image
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: build package
        run: |
          export TWINE_USERNAME=${{secrets.TWINE_USERNAME}}
          export TWINE_PASSWORD=${{secrets.TWINE_PASSWORD}}

          python setup.py sdist bdist_wheel
          twine upload dist/*


  