name: Packaging
 
on: 
  push:
    branches: [main]

jobs:
  build-packaging-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: yekhanfir/id-mlip
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile.packaging
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      

  publish-mlip-package:
    needs: build-packaging-image
    runs-on: ubuntu-latest

    container:
      image: yekhanfir/id-mlip:latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: build package
      #   run: |
      #     export TWINE_USERNAME=__token__
      #     export TWINE_PASSWORD=${{secrets.TWINE_ACCESS_TOKEN}}

      #     python setup.py sdist bdist_wheel
      #     twine upload dist/*




  