name: Package publishing

on:
  push:
    branches: [main]

jobs:
  publish-new-mlip-release:
    runs-on: ubuntu-latest

    container:
       image: python:3.10.12-slim-bullseye

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup
        run: |
          apt-get update && apt-get install -y \
          coreutils \
          curl \

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: build and publish
        run: |
          export UV_PYPI_TOKEN_PYPI=${{secrets.TWINE_ACCESS_TOKEN}}
          uv publish
